
train:
  env: point_mass
  max_episode: 1000
  max_sequence: 100
  save_path: datasets/sample/point_mass
  save_filename: train.npz

test:
  max_episode: 1
  max_sequence: 100
  save_path: datasets/sample/point_mass
  save_filename: test.npz
