batch_size: &batch_size 1
epoch_size: 300 
check_epoch: 10
bit_depth: &bit_depth 8
device: &device cuda
path: &path datasets/real_world


weight:
  path: results/2023_05_31_14_05_15/weights
  filename: 300.weight


environment:
  domain_name: ycb_mass
  task_name: easy
  max_episode_length: 900
  bit_depth: 8


model:
  delta_time: &delta_time 0.5
  clip_grad_norm: False
  clip_grad_value: False
  device: *device
  use_amp: False

  encoder_param:
    input_dim: 3
    label_dim: 9
    output_dim: 2
    activate_func: ReLU

  decoder_param:
    input_dim: 2
    label_dim: 9
    output_dim: 3
    activate_func: LeakyReLU

  transition_param:
    delta_time: *delta_time

  velocity_param:
    batch_size: *batch_size
    activate_func: ReLU
    delta_time: *delta_time
    device: *device
    use_data_efficiency: True

  optimizer: Adam
  optimizer_params:
    lr: 0.0003


dataset:
  train:
    episode_size: &train_episode_size 900
    sequence_size: &trin_sequence_size 10

    data:
      path: *path
      filename: dataset.train.npz

    memory:
      episode_size: *train_episode_size
      sequence_size: *trin_sequence_size
      action_size: 2
      bit_depth: *bit_depth
      device: *device

    loader:
      batch_size: 9
      shuffle: True
      drop_last: False
      num_workers: 8
      pin_memory: True

  validation:
    episode_size: &validation_episode_size 90
    sequence_size: &validation_sequence_size 20

    data:
      path: *path
      filename: dataset.validation.npz

    memory:
      episode_size: *validation_episode_size
      sequence_size: *validation_sequence_size
      action_size: 2
      bit_depth: *bit_depth
      device: *device

    loader:
      batch_size: 1
      shuffle: False
      drop_last: False
      num_workers: 8
      pin_memory: True
