load_path: &save_path datasets/sample/point_mass_100
device: &device cuda:0


weight:
  path: results/2022_12_07_03_56_04/weights
  filename: 300.weight


dataset:
  test:
    episode_size: &episode_size 100
    sequence_size: &sequence_size 100
    data:
      path: *save_path
      filename: test.npz

    memory:
      episode_size: *episode_size
      sequence_size: *sequence_size
      action_size: 2
      device: *device

    test_loader:
      batch_size: 1
      shuffle: False
      drop_last: False


model:
  delta_time: &delta_time 0.5
  clip_grad_norm: False
  clip_grad_value: False
  device: *device
  use_amp: True

  encoder_param:
    input_dim: 3
    output_dim: 2
    act_func_name: ReLU

  decoder_param:
    input_dim: 2
    output_dim: 3
    act_func_name: LeakyReLU
    device: *device

  transition_param:
    delta_time: *delta_time

  velocity_param:
    act_func_name: ReLU
    delta_time: *delta_time

  optimizer: Adam
  optimizer_params:
    lr: 0.0003
