env: reacher_nvae

train:
  max_episode: 1000
  max_sequence: 100
  save_path: datasets/sample
  save_filename: train.npz

test:
  max_episode: 1
  max_sequence: 100
  save_path: datasets/sample
  save_filename: test.npz
