batch_size: &batch_size 8
epoch_size: 300 
check_epoch: 1
bit_depth: &bit_depth 8
device: &device cuda:0
path: &path datasets/mustard_bottle_and_tomato_soup_can


weight:
  path: results/test/weights/250.weight

path: results/2023_10_27_13_04_12/weights/250.weight


environment:
  domain_name: ycb_mass
  task_name: easy
  max_episode_length: 1000
  bit_depth: 8


model:
  delta_time: &delta_time 0.5
  clip_grad_norm: False
  clip_grad_value: False
  device: *device
  use_amp: False

  encoder_param:
    input_dim: 3
    label_dim: 2
    output_dim: 3
    activate_func: Mish

  decoder_param:
    input_dim: 3
    label_dim: 2
    output_dim: 3
    activate_func: LeakyReLU

  transition_param:
    delta_time: *delta_time

  velocity_param:
    batch_size: *batch_size
    act_func_name: ReLU
    delta_time: *delta_time
    device: *device
    use_data_efficiency: True

  optimizer: Adam
  optimizer_params:
    lr: 0.0003


dataset:
  train:
    episode_size: &train_episode_size 1000
    sequence_size: &trin_sequence_size 100

    data:
      path: *path
      filename: train.npz

    memory:
      episode_size: *train_episode_size
      sequence_size: *trin_sequence_size
      action_size: 3
      bit_depth: *bit_depth
      device: *device

    loader:
      batch_size: 1
      shuffle: True
      drop_last: False
      num_workers: 8
      pin_memory: True

  validation:
    episode_size: &validation_episode_size 100
    sequence_size: &validation_sequence_size 100

    data:
      path: *path
      filename: validation.npz

    memory:
      episode_size: *validation_episode_size
      sequence_size: *validation_sequence_size
      action_size: 3
      bit_depth: *bit_depth
      device: *device

    loader:
      batch_size: 16
      shuffle: False
      drop_last: False
      num_workers: 8
      pin_memory: True

  test:
    episode_size: &test_episode_size 20
    sequence_size: &test_sequence_size 100
    data:
      path: *path
      filename: test.npz

    memory:
      episode_size: *test_episode_size
      sequence_size: *test_sequence_size
      action_size: 3
      bit_depth: *bit_depth
      device: *device

    loader:
      batch_size: 1
      shuffle: False
      drop_last: False
      num_workers: 8
      pin_memory: True
